//
// Generated file, do not edit! Created by opp_msgc 4.3 from LabMsg.msg.
//

#ifndef _LABMSG_M_H_
#define _LABMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>LabMsg.msg</tt> by opp_msgc.
 * <pre>
 * message LabMsg {
 *     string dst;
 *     string src;
 *     int sessionId;
 *     int packetId;
 *     int priority = 0;
 *     string payload;
 * }
 * </pre>
 */
class LabMsg : public ::cMessage
{
  protected:
    opp_string dst_var;
    opp_string src_var;
    int sessionId_var;
    int packetId_var;
    int priority_var;
    opp_string payload_var;

  private:
    void copy(const LabMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LabMsg&);

  public:
    LabMsg(const char *name=NULL, int kind=0);
    LabMsg(const LabMsg& other);
    virtual ~LabMsg();
    LabMsg& operator=(const LabMsg& other);
    virtual LabMsg *dup() const {return new LabMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDst() const;
    virtual void setDst(const char * dst);
    virtual const char * getSrc() const;
    virtual void setSrc(const char * src);
    virtual int getSessionId() const;
    virtual void setSessionId(int sessionId);
    virtual int getPacketId() const;
    virtual void setPacketId(int packetId);
    virtual int getPriority() const;
    virtual void setPriority(int priority);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doPacking(cCommBuffer *b, LabMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, LabMsg& obj) {obj.parsimUnpack(b);}


#endif // _LABMSG_M_H_
